#!/bin/bash

set -x

deploy_list=$1
name=$2
version=$3

line=$(grep "^$name" $deploy_list)

hostname=$(echo $line | cut -d' ' -f2)
username=$(echo $line | cut -d' ' -f3)
vortexpath=$(echo $line | cut -d' ' -f4)

if [ "$version" = "olive-dev" ]; then
     vortex_link=$vortexpath/vortex-olive
else
    vortex_link=$vortexpath/vortex
fi

verno=$(echo $version | sed "s/^v//")

git archive HEAD --prefix vortex-$verno/ -o vortex-$verno.tar
bzip2 vortex-$verno.tar
rsync -a vortex-$verno.tar.bz2 ${username}@${hostname}:$vortexpath/
ssh ${username}@${hostname} "(cd $vortexpath/; tar -xf vortex-$verno.tar.bz2)"
ssh ${username}@${hostname} "rm -f $vortex_link; ln -s vortex-$verno $vortex_link"
