name: Lint, format and tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - run: pip install ruff==0.9.*
    - run: ruff check src/

  ruff-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - run: pip install ruff==0.9.*
    - run: ruff format --check src/

